CREATE DATABASE DataDigger;
USE DataDigger;

#CREATING CUTOMERS TABLE
CREATE TABLE customers(
CustomerID INT AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(100) NOT NULL ,
Email VARCHAR(100) NOT NULL,
Address VARCHAR(150) NOT NULL
);

#CREATING ORDERS TABLE 
CREATE TABLE orders(
OrderID INT AUTO_INCREMENT PRIMARY KEY,
CustomerID INT NOT NULL,
OrderDate DATE NOT NULL,
TotalAmount DECIMAL(10,2) NOT NULL,
FOREIGN KEY (CustomerID) REFERENCES customers(CustomerID)
);

#CREATING PRODUCTS TABLE
CREATE TABLE products(
ProductID INT AUTO_INCREMENT PRIMARY KEY,
ProductName VARCHAR(100) NOT NULL,
Price DECIMAL(10,2) NOT NULL,
Stock INT NOT NULL
);

#CREATING ORDER DETAILS TABLE
CREATE TABLE orderdetails(
OrderDetailID INT AUTO_INCREMENT PRIMARY KEY,
OrderID INT NOT NULL,
ProductID INT NOT NULL,
Quantity INT NOT NULL,
SubTotal DECIMAL(10,2) NOT NULL,
FOREIGN KEY (OrderID) 
REFERENCES orders(OrderID),
FOREIGN KEY (ProductID) 
REFERENCES products(ProductID)
);

#INSERTING DATA INTO CUSTOMERS
INSERT INTO customers (Name,Email,Address) VALUES
("Vaidik","vaidik123@gmail.com","Vastral"),
("Ved","ved43@gmail.com","Khokhra"),
("Vineet","vineet21@gmail.com","Maninagar"),
("Jay","jay56@gmail.com","C.T.M."),
("Pooja","pooja456@gmail.com","Gandhinagar");

INSERT INTO CUSTOMERS (NAME,EMAIL,ADDRESS) VALUES
("Karan","karan43@gmail.com","Ramol");

#CUSTOMER QUERIES

#RETIREVE ALL CUSTOMERS
SELECT * FROM customers;

#UPDATE CUSTOMERS ADDRESS
UPDATE customers
SET Address="Nikol"
WHERE Address="C.T.M.";

#DELETE A CUSTOMER USING THEIR CUSTOMERID
DELETE FROM customers
WHERE CustomerID=2;

#DISPLAY ALL CUSTOMER WHOSE NAME IS SOMEONES NAME
SELECT * FROM customers
WHERE Name="Vaidik";

#INSERTING THE DATA INTO ORDERS
INSERT INTO orders(CustomerID,OrderDate, TotalAmount) VALUES
(1,CURDATE()-INTERVAL 5 DAY, 1500.00),
(3,CURDATE()-INTERVAL 10 DAY,750.00),
(4,CURDATE()-INTERVAL 14 DAY,950.00),
(5,CURDATE()-INTERVAL 25 DAY,450.00),
(6,CURDATE()-INTERVAL 35 DAY,1800.00);

#ORDERS QUERIES

#RETRIEVE ALL ORDERS MADE BY A SPECIFIC CUSTOMER
SELECT * FROM orders 
WHERE CustomerID=1;

#UPATE AN ORDER'S TOTAL AMOUNT 
UPDATE orders
SET TotalAmount=1650.00
WHERE CustomerID=5;

#DELETE AN ORDER USING ITS ORDERID
DELETE FROM orders
WHERE OrderID=6;

#RETRIEVE ORDER PLACED IN THE LAST 30 DAYS
SELECT * FROM orders
WHERE OrderDate>=CURDATE()- INTERVAL 30 DAY;

#INSERTING DATA INTO PRODUCTS 
INSERT INTO products (ProductName,Price,Stock) VALUES
("Wireless Mouce",799.00,25),
("Mechanical Keyboard",1899.00,15),
("Laptop Charger",999.00,30),
("Laptop Stand",1499.00,10),
("Webcam",1299.00,0);

#PRODUCTS QUERIES 

#PRODUCT SORTED BY PRICE DESCENDING
SELECT * FROM PRODUCTS 
ORDER BY Price DESC;

#UPDATE PRICE OF PRODUCT
UPDATE products
SET Price=1499.00
WHERE ProductID=5;

#PRODUCTS BETWEEN ₹500 AND ₹2000
SELECT * FROM products 
WHERE Price BETWEEN 500 AND 2000;

#MOST EXPENSIVE PRODUCT 
SELECT * FROM products 
WHERE Price=(SELECT MAX(Price) FROM products);

#CHEAPEST PRODUCT
SELECT * FROM products 
WHERE Price=(SELECT MIN(Price) FROM products);

#DELETE PRODUCT IF IT IS OUT OF STOCK
DELETE FROM products
WHERE productID=5 AND Stock=0;


#INSERTING ORDER DETAILS DATA
INSERT INTO orderdetails (OrderID,ProductID,Quantity,SubTotal) VALUES
(7,1,1,799.00),
(8,2,1,1899.00),
(9,3,1,999.00),
(10,4,1,1499.00);

#ORDER DETAILS QUERIES

#DETAILS FOR A SPECIFIC ORDER
SELECT * FROM OrderDetails 
WHERE OrderID=7;

#TOTAL REVENUE
SELECT SUM(SubTotal) AS TotalRevene FROM OrderDetails;

#TOP 3 MOST ORDERED PRODUCTS
SELECT P.ProductID,P.ProductName,SUM(OD.Quantity) AS TotalQuantityOrdered
FROM orderdetails OD
JOIN products P
ON OD.ProductID=P.ProductID
GROUP BY P.ProductID,P.ProductName 
ORDER BY TotalQuantityOrdered DESC LIMIT 3;             SELECT * FROM CUSTOMERS

#COUNT HOW MANY TIMES PRODUCTID 2WAS SOLD
SELECT  ProductID,COUNT(*) AS TIMESOLD
FROM OrderDetails
WHERE  ProductID=2
GROUP BY ProductID;


## DELETION EXAMPLES

#FIRST DELETE ORDERDETAILS BELONGING TO ORDER 7
DELETE FROM OrderDetails WHERE OrderID=7;

#THEN DELETE ORDER 7
DELETE FROM Orders WHERE OrderID=7;

#FINALLY DELETE CUSTOMER 7
DELETE  FROM customers
WHERE CustomerID=7;

#FINAL VERIFICATION

SELECT * FROM customers;
SELECT * FROM orders;
SELECT * FROM products;
SELECT * FROM orderdetails;